selected_model: gpt-oss-120b-4bit

training:
  num_train_epochs: 3
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  learning_rate: 2e-5
  warmup_steps: 100
  logging_steps: 10
  save_steps: 500
  save_total_limit: 3
  eval_steps: 500
  fp16: false
  bf16: true
  optim: adamw_8bit
  weight_decay: 0.01
  lr_scheduler_type: cosine
  max_grad_norm: 1.0
  seed: 3407
  group_by_length: true
  report_to: tensorboard

lora:
  r: 64
  lora_alpha: 128
  lora_dropout: 0.05
  bias: none
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
  use_gradient_checkpointing: unsloth
  random_state: 3407
  use_rslora: true

generation:
  max_new_tokens: 512
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  repetition_penalty: 1.1
